version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "npb-source-bucket"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-13e1sa9930l7j"
s3_prefix = "npb-source-bucket"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
